apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-northeast-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large #try t2.medium
    desiredCapacity: 1

  #if you want to add second node group.
  #- name: ng-2
  #  instanceType: m5.large
  #  desiredCapacity: 2

#just run "eksctl create cluster -f cluster.yaml"
# reference:https://qiita.com/purini-to/items/89cf41ed6ac02c1114bc
