version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata
volumes:
  mongodata:
    driver: local