version: '3'

services:
  web:
    build: .
    volumes:
      - .:/scraping #->.json path is /scraping/app/events.json
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    tty: true
    environment:
      - MONGO_SERVER=mongodb   #NOT host.docker.internal
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodata
    ports:
      - "27016:27017" #local uses port 27016 to port forward.
    command:
      - sh
      - sleep 3600
volumes:
  mongodata:
    driver: local