apiVersion: apps/v1
kind: Deployment
metadata:
  name: builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
        - name: builder
          image: kenobata/golang-scraping:latest # is this right?
          ports:
            - containerPort: 80 # changed from 80->8080
          env: # POD's environment setting for const
          - name: MONGO_SERVER
            value: mongo.default.svc.cluster.local.  # <-host.docker.internal #mongo comes from app name of volume
          - name: REDIS_SERVER
            value: redis.default.svc.cluster.local