apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem #Do we need to use Block insetead? -> Not now.
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2

  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-01130ed53cbb1f9c8"
    #"vol-01d01a7abb17f2172" #this is from aws ec2 create-volume xxx
  #this is a kubernetes volume. We need a AWS volume first.

