apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2

  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-03f01829463f36a2b" #this is from aws ec2 create-volume xxx
  #this is a kubernetes volume. We need a AWS volume first.

