apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-slow-claim #this is ganna be a .yaml name of pod!
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow