apiVersion: v1
kind: Pod
metadata:
  name: pvc-slow-test # we ganna type "kubectl exec pvc-slow-test -- ls -l"
spec:
  containers:
    - image: alpine
      name: alpine
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: claim-volume
          mountPath: /data
  volumes:
    - name: claim-volume
      persistentVolumeClaim:
        claimName: pv-slow-claim
  terminationGracePeriodSeconds: 0
