name: main

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mongo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
    
      - name: Test
        env:
          MONGO_SERVER: mongo
        run: go test -v ./...
